server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:h2:./data/test;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
    show-sql: true
  h2:
    console:
      enabled: true  # Włącz konsolę H2
      path: /h2       # Ścieżka do konsoli H2 (domyślnie /h2)

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
